class TokenView:
    """Lightweight token view into source text (read-only)."""

    # Read-only properties
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def text(self) -> str: ...
    @property
    def kind(self) -> int: ...

def tokenize(source: str) -> list[TokenView]: ...
